name: CI

on: 
  push: 
    branches: [main, dev]
    paths: [ "**/*.cs" ]

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Format
        run: dotnet format --verfiy-no-changes --verbosity diagnostic
